<html>
   
   <head>
   <title>Register</title>
   <style>
   
   .feature td{
	   
	   text-align:center;
	  
	   
	
   }
   .button{
            padding:5px;
            background-color: #ec6a54;
            height:50px;
            width:150px;
            border: 1px solid #666;
            color:#000;
            text-decoration:none;
            margin-top:15px;


          }  
   
   </style>
   </head>
   
   <body>
      <center><h1><u>Feature List</u></h1></center>
       <table class="feature" frame="box" style="width:80%;margin:auto;">
          <tr>
          <th>SI No.</th>
          <th>Feature</th>
          <th>Standard</th>
          <th>Premium</th>
          </tr>
          
          <tr>
          <td>1</td>
          <td>One Window Fulfilment Proces</td>
          <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
          <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
          
          </tr>
          
          <tr>
		  <td>2</td>
          <td>Customised Buying Catalog (e-store for your company)</td>
          <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
          <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
          </tr>
       <tr>
         <td>3</td>
         <td>Privilege Pricing Program</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/cross.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
         <td>4</td>
         <td>Customized Approval Process</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
		 <td>5</td>
         <td>Online RFP Process</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
         <td>6</td>
         <td>Multi Location Delivery</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
         <td>7</td>
         <td>MIS Dashboard and Forecasting tool</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
         <td>8</td>
         <td>Payment Terms</td>
         <td>COD/NEFT/Credit Cards</td>
         <td>COD/NEFT/Credit Cards/Credit Terms</td>
       </tr>
       
       
       <tr>
       
         <td>9</td>
         <td>On Demand Services</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       
       </tr>
       
       
       <tr>
       
         <td>10</td>
         <td>Online Delivery Tracking</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       
       </tr>
       
       <tr>
       
         <td>11</td>
         <td>Secured Transaction</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       
       <tr>
         <td>12</td>
         <td>Loyalty Rewards Program</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
		  <td>13</td>
         <td>Flexible procurement facility</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/cross.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       
       </tr>
       
       <tr>
		 <td>14</td>
         <td>Dedicted Account Manager</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/cross.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       
       </tr>
       
       <tr>
       <td>15</td>
       <td>Concierge Helpdesk</td>
       <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/cross.png" height="35" width="35"></td>
       <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
         <td>16</td>
         <td>Easy Returns</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/cross.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
       
         <td>17</td>
         <td>Express Delivery</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       <tr>
         <td>18</td>
         <td>Smart Shipping Calculator</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       
       </tr>
       
       <tr>
         <td>19</td>
         <td>Easy Checkout</td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
         <td><img src="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/media/custom/tick.png" height="35" width="35"></td>
       </tr>
       
       </table>
   
       <center><a href="http://ec2-52-77-248-237.ap-southeast-1.compute.amazonaws.com/index.php/customer/account/create/"><button class="button">Register</button></a></center>
   
   </body>


</html>
