<?php if ($this->isEnabled()): ?>
    <button type="button" style="margin-top:30px;" title="<?php echo $this->__('Request quote') ?>" id="<?php echo time(); ?>"
            class="quote-request-button button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()): ?> no-checkout<?php endif; ?>" 
            onclick="ajaxOpenDialog('<?php echo $this->getRequestQuoteFormHtmlUrl(); ?>');"
        <?php if ($this->isDisabled()): ?> disabled="disabled"<?php endif; ?>>
        <span><span><?php echo $this->__('Request quote') ?></span></span></button>

<?php endif; ?>